lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views  #1
from lists import urls as list_urls  #2

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import render
from django.http import HttpResponse
from lists.models import Item, List

from django.shortcuts import redirect, render
from lists.models import Item

from django.core.exceptions import ValidationError


def home_page(request):
    return render(request, 'home.html')

    
    
def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    
    items = Item.objects.filter(list=list_)
    counter = items.count()
    status = "oh tidak"
    error = None
    
    if counter == 0:
        status = "yey, waktunya berlibur"
    elif counter < 5:
        status = "sibuk tapi santai"
    else:
        status = "oh tidak"
        
    if request.method == 'POST':
        try:
            item = Item(text=request.POST['item_text'], list=list_)
            item.full_clean()
            item.save()
            return redirect(list_)
        except ValidationError:
            error = "You can't have an empty list item"
            
    return render(request, 'list.html', {'status':status,'list': list_,'error': error})
    
        
def new_list(request):
    list_ = List.objects.create()
    item = Item(text=request.POST['item_text'], list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list item"
        return render(request, 'home.html', {"error": error})
    return redirect(list_)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>

<body>
	
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
  
                <div class="navbar-brand"> Ridwan Arvihafiz Bakri - 1206208050</div>
            </div>

            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<div class="container">

    <div class="row">
		<div class="col-md-6 col-md-offset-3 jumbotron">
        	<div class="text-center">
            	<h1>{% block header_text %}{% endblock %}</h1>
            	
				<form method="POST" action="{% block form_action %}{% endblock %}">
				    <input name="item_text" id="id_new_item"
				           class="form-control input-lg"
				           placeholder="Enter a to-do item"
				    />
				    {% csrf_token %}
				    {% if error %}
				        <div class="form-group has-error">
				            <span class="help-block">{{ error }}</span>
				        </div>
				    {% endif %}
				</form>
				<br/>
		    	<p>Komentar : {% block komentar %}</p>
				{% endblock %}
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>

</div>
</body>

</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block komentar %}yey, waktunya berlibur{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block komentar %} {{status}} {% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}